spring:
  datasource:
    url: jdbc:mysql://172.17.9.101:3306/etcd?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-timeout: 5000
    idle-timeout: 12000
    max-lifetime: 900000
    minimum-idle: 5
    maximum-pool-size: 20
    connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  messages:
    basename: validation
server:
  port: 8001
